version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - bartfeenstra
    commit-message:
      prefix: GitHub Actions dependencies
      include: scope
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    assignees:
      - bartfeenstra
    commit-message:
      prefix: pip dependencies
      include: scope
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    assignees:
      - bartfeenstra
    commit-message:
      prefix: npm dependencies (development)
      include: scope
  - package-ecosystem: npm
    directory: js
    schedule:
      interval: daily
    assignees:
      - bartfeenstra
    commit-message:
      prefix: npm dependencies (Betty built-in)
      include: scope
  - package-ecosystem: npm
    directory: betty/data/webpack/http-api-doc/
    ignore:
      - dependency-name: "@betty.py/betty"
    schedule:
      interval: daily
    assignees:
      - bartfeenstra
    commit-message:
      prefix: npm dependencies (HttpApiDoc extension)
      include: scope
  - package-ecosystem: npm
    directory: betty/data/webpack/maps/
    ignore:
      - dependency-name: "@betty.py/betty"
    schedule:
      interval: daily
    assignees:
      - bartfeenstra
    commit-message:
      prefix: npm dependencies (Maps extension)
      include: scope
  - package-ecosystem: npm
    directory: betty/data/webpack/raspberry-mint/
    ignore:
      - dependency-name: "@betty.py/betty"
    schedule:
      interval: daily
    assignees:
      - bartfeenstra
    commit-message:
      prefix: npm dependencies (Raspberry Mint extension)
      include: scope
  - package-ecosystem: npm
    directory: betty/data/webpack/trees/
    ignore:
      - dependency-name: "@betty.py/betty"
    schedule:
      interval: daily
    assignees:
      - bartfeenstra
    commit-message:
      prefix: npm dependencies (Trees extension)
      include: scope
  - package-ecosystem: npm
    directory: betty/data/webpack/webpack/
    ignore:
      - dependency-name: "@betty.py/betty"
    schedule:
      interval: daily
    assignees:
      - bartfeenstra
    commit-message:
      prefix: npm dependencies (Webpack extension)
      include: scope
