version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - bartfeenstra
    commit-message:
      prefix: GitHub Actions dependencies
      include: scope
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    assignees:
      - bartfeenstra
    commit-message:
      prefix: pip dependencies
      include: scope
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    assignees:
      - bartfeenstra
    commit-message:
      prefix: npm dependencies (development)
      include: scope
  - package-ecosystem: npm
    directory: js
    schedule:
      interval: weekly
    assignees:
      - bartfeenstra
    commit-message:
      prefix: npm dependencies (Betty library)
      include: scope
  - package-ecosystem: npm
    directory: betty/plugins/extension/http_api_doc/webpack/
    ignore:
      - dependency-name: "@betty.py/betty"
    schedule:
      interval: weekly
    assignees:
      - bartfeenstra
    commit-message:
      prefix: npm dependencies (HttpApiDoc extension)
      include: scope
  - package-ecosystem: npm
    directory: betty/plugins/extension/maps/webpack/
    ignore:
      - dependency-name: "@betty.py/betty"
    schedule:
      interval: weekly
    assignees:
      - bartfeenstra
    commit-message:
      prefix: npm dependencies (Maps extension)
      include: scope
  - package-ecosystem: npm
    directory: betty/plugins/extension/raspberry_mint/webpack/
    ignore:
      - dependency-name: "@betty.py/betty"
    schedule:
      interval: weekly
    assignees:
      - bartfeenstra
    commit-message:
      prefix: npm dependencies (Raspberry Mint extension)
      include: scope
  - package-ecosystem: npm
    directory: betty/plugins/extension/trees/webpack/
    ignore:
      - dependency-name: "@betty.py/betty"
    schedule:
      interval: weekly
    assignees:
      - bartfeenstra
    commit-message:
      prefix: npm dependencies (Trees extension)
      include: scope
