version: 2
build:
  os: ubuntu-22.04
  tools:
    python: '3.12'
  jobs:
    pre_build:
      - sphinx-apidoc --force --separate -d 999 -o documentation betty betty/tests
sphinx:
  configuration: documentation/conf.py
python:
  install:
    - method: pip
      path: .
