target-version = 'py313'
[lint]
extend-select = [
    'A',
    'B',
    'C4',
    'D',
    'F',
    'FA',
    'I',
    'INT',
    'LOG',
    'PIE',
    'PT',
    'PTH',
    'RET',
    'SIM',
    'SLOT',
    'T20',
    'TC',
    'UP',
    'RUF022',
]
ignore = [
    'A005',
    'D105',
    'D107',
    'D200',
    'D203',
    'D212',
    'D401',
    'PTH123',
    'TC006',
]

[lint.per-file-ignores]
"betty/tests/*" = [
    'D100',
    'D101',
    'D102',
    'D103',
    'D104',
    'D106',
]
"bin/*" = [
    'PTH109',
    'PTH118',
]
