target-version = 'py313'
[lint]
select = [
    'A001',
    'A002',
    'A003',
    'A004',
    'A006',
    'ANN001',
    'ANN002',
    'ANN003',
    'ANN201',
    'ANN202',
    'ANN205',
    'ANN206',
    'B002',
    'B003',
    'B004',
    'B005',
    'B006',
    'B007',
    'B008',
    'B009',
    'B010',
    'B011',
    'B012',
    'B013',
    'B014',
    'B015',
    'B016',
    'B017',
    'B018',
    'B019',
    'B020',
    'B021',
    'B022',
    'B023',
    'B024',
    'B025',
    'B026',
    'B027',
    'B028',
    'B029',
    'B030',
    'B031',
    'B032',
    'B033',
    'B034',
    'B035',
    'B039',
    'B043',
    'B901',
    'B903',
    'B904',
    'B905',
    'B909',
    'B911',
    'B912',
    'C400',
    'C401',
    'C402',
    'C403',
    'C404',
    'C405',
    'C406',
    'C408',
    'C409',
    'C410',
    'C411',
    'C413',
    'C414',
    'C415',
    'C416',
    'C418',
    'C419',
    'C420',
    'D100',
    'D101',
    'D102',
    'D103',
    'D104',
    'D106',
    'D201',
    'D202',
    'D204',
    'D205',
    'D206',
    'D207',
    'D208',
    'D209',
    'D210',
    'D211',
    'D213',
    'D214',
    'D215',
    'D300',
    'D301',
    'D400',
    'D402',
    'D403',
    'D404',
    'D405',
    'D406',
    'D407',
    'D408',
    'D409',
    'D410',
    'D411',
    'D412',
    'D413',
    'D414',
    'D415',
    'D416',
    'D417',
    'D418',
    'D419',
    'D420',
    'DTZ001',
    'DTZ002',
    'DTZ003',
    'DTZ004',
    'DTZ005',
    'DTZ006',
    'DTZ007',
    'DTZ011',
    'DTZ012',
    'DTZ901',
    'F401',
    'F402',
    'F403',
    'F404',
    'F405',
    'F406',
    'F407',
    'F501',
    'F502',
    'F503',
    'F504',
    'F505',
    'F506',
    'F507',
    'F507',
    'F509',
    'F521',
    'F522',
    'F523',
    'F524',
    'F525',
    'F541',
    'F601',
    'F602',
    'F621',
    'F622',
    'F631',
    'F632',
    'F633',
    'F634',
    'F701',
    'F702',
    'F704',
    'F706',
    'F707',
    'F811',
    'F821',
    'F822',
    'F823',
    'F841',
    'F842',
    'F901',
    'FA100',
    'FA102',
    'I001',
    'I002',
    'INT001',
    'INT002',
    'INT003',
    'LOG001',
    'LOG002',
    'LOG004',
    'LOG007',
    'LOG009',
    'LOG014',
    'LOG015',
    'PIE790',
    'PIE794',
    'PIE796',
    'PIE800',
    'PIE804',
    'PIE807',
    'PIE808',
    'PIE810',
    'PLC1802',
    'PLC0205',
    'PLR1704',
    'PLR1716',
    'PLR5501',
    'PLW0108',
    'PLW0245',
    'PLW0602',
    'PLW1501',
    'PLW1508',
    'PLW1514',
    'PLW2901',
    'PT001',
    'PT002',
    'PT003',
    'PT006',
    'PT008',
    'PT009',
    'PT010',
    'PT011',
    'PT012',
    'PT013',
    'PT014',
    'PT015',
    'PT016',
    'PT017',
    'PT018',
    'PT019',
    'PT020',
    'PT021',
    'PT022',
    'PT023',
    'PT024',
    'PT025',
    'PT026',
    'PT027',
    'PT028',
    'PT029',
    'PT030',
    'PT031',
    'PTH100',
    'PTH101',
    'PTH102',
    'PTH103',
    'PTH104',
    'PTH105',
    'PTH106',
    'PTH107',
    'PTH108',
    'PTH109',
    'PTH110',
    'PTH111',
    'PTH112',
    'PTH113',
    'PTH114',
    'PTH115',
    'PTH116',
    'PTH117',
    'PTH118',
    'PTH119',
    'PTH120',
    'PTH121',
    'PTH122',
    'PTH124',
    'PTH201',
    'PTH202',
    'PTH203',
    'PTH204',
    'PTH205',
    'PTH206',
    'PTH207',
    'PTH208',
    'PTH210',
    'PTH211',
    'PYI001',
    'PYI002',
    'PYI003',
    'PYI004',
    'PYI005',
    'PYI006',
    'PYI007',
    'PYI008',
    'PYI009',
    'PYI010',
    'PYI011',
    'PYI012',
    'PYI013',
    'PYI014',
    'PYI015',
    'PYI016',
    'PYI017',
    'PYI018',
    'PYI019',
    'PYI020',
    'PYI021',
    'PYI024',
    'PYI026',
    'PYI029',
    'PYI030',
    'PYI032',
    'PYI033',
    'PYI034',
    'PYI035',
    'PYI036',
    'PYI041',
    'PYI042',
    'PYI043',
    'PYI044',
    'PYI045',
    'PYI046',
    'PYI047',
    'PYI048',
    'PYI049',
    'PYI050',
    'PYI051',
    'PYI052',
    'PYI053',
    'PYI054',
    'PYI055',
    'PYI056',
    'PYI057',
    'PYI058',
    'PYI059',
    'PYI061',
    'PYI062',
    'PYI063',
    'PYI064',
    'PYI066',
    'RET501',
    'RET502',
    'RET503',
    'RET504',
    'RET505',
    'RET506',
    'RET507',
    'RET508',
    'RUF012',
    'RUF022',
    'SIM101',
    'SIM102',
    'SIM103',
    'SIM105',
    'SIM107',
    'SIM108',
    'SIM109',
    'SIM110',
    'SIM112',
    'SIM113',
    'SIM114',
    'SIM115',
    'SIM116',
    'SIM117',
    'SIM118',
    'SIM201',
    'SIM202',
    'SIM208',
    'SIM210',
    'SIM211',
    'SIM212',
    'SIM220',
    'SIM221',
    'SIM222',
    'SIM223',
    'SIM300',
    'SIM401',
    'SIM905',
    'SIM910',
    'SIM911',
    'SLOT000',
    'SLOT001',
    'SLOT002',
    'T201',
    'T203',
    'TC001',
    'TC002',
    'TC003',
    'TC004',
    'TC005',
    'TC007',
    'TC008',
    'TC010',
    'TRY002',
    'TRY201',
    'TRY203',
    'TRY300',
    'TRY301',
    'TRY400',
    'TRY401',
    'UP011',
    'UP012',
    'UP013',
    'UP014',
    'UP015',
    'UP017',
    'UP018',
    'UP019',
    'UP020',
    'UP021',
    'UP022',
    'UP023',
    'UP024',
    'UP025',
    'UP026',
    'UP028',
    'UP029',
    'UP030',
    'UP031',
    'UP032',
    'UP033',
    'UP034',
    'UP035',
    'UP036',
    'UP037',
    'UP039',
    'UP040',
    'UP041',
    'UP042',
    'UP043',
    'UP044',
    'UP045',
    'UP046',
    'UP047',
    'UP049',
    'UP050',
]

[lint.per-file-ignores]
"betty/tests/*" = [
    'D100',
    'D101',
    'D102',
    'D103',
    'D104',
    'D106',
]
"bin/*" = [
    'PTH109',
    'PTH118',
]
