[lint]
extend-select = [
    'A',
    'B',
    'C4',
    'D',
    'F',
    'INT',
    'PT',
    'PTH',
    'SIM',
    'SLOT',
    'T20',
    'TCH',
]
ignore = [
    'D105',
    'D107',
    'D200',
    'D203',
    'D212',
    'D401',
    'F501',
    'PTH123',
]

[lint.per-file-ignores]
"betty/tests/*" = [
    'D100',
    'D101',
    'D102',
    'D103',
    'D104',
    'D106',
]
