[build-system]
requires = [
    'setuptools ~= 82.0',
]
build-backend = 'setuptools.build_meta'

[project]
version = '0.0.0'
name = 'betty'
description = 'Betty visualizes and publishes your family history by building interactive, encyclopedia-like genealogy websites out of your Gramps and GEDCOM family trees'
readme = 'README.md'
license = 'GPL-3.0-or-later'
license-files = ['LICENSE.txt']
authors = [
  {name = 'Bart Feenstra', email = 'bar@bartfeenstra.com'},
]
requires-python = '~= 3.13'
dependencies = [
    # aiohttp-client-cache's file backend requires aiofiles.
    'aiofiles ~= 25.1',
    'aiohttp ~= 3.12',
    'aiohttp-client-cache ~= 0.14',
    'aiosqlite ~= 0.21',
    'babel ~= 2.16',
    'docutils ~= 0.21',
    'geopy ~= 2.4',
    'jinja2 ~= 3.1',
    'jsonschema ~= 4.23',
    'lxml ~= 7.0.0a1',
    'markupsafe ~= 3.0',
    'pdf2image ~= 1.17',
    'polib ~= 1.2',
    'Pillow ~= 12.0',
    'platformdirs ~= 4.3',
    'pyyaml ~= 6.0',
    'referencing ~= 0.37.0',
    'rich ~= 15.0',
    'rich-argparse ~= 1.7',
    'shibuya == 2026.5.19',
    'sphinx ~= 8.2',
    'sphinx-design ~= 0.7.0',
]
classifiers = [
    'Environment :: Console',
    'Intended Audience :: Developers',
    'Intended Audience :: End Users/Desktop',
    'Intended Audience :: Science/Research',
    'Programming Language :: JavaScript',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
    'Programming Language :: Python :: 3.15',
    'Operating System :: MacOS :: MacOS X',
    'Operating System :: POSIX :: Linux',
    'Operating System :: Microsoft :: Windows',
    'Topic :: Internet',
    'Topic :: Scientific/Engineering :: Visualization',
    'Topic :: Sociology :: Genealogy',
    'Topic :: Sociology :: History',
    'Topic :: Software Development :: Code Generators',
    'Natural Language :: Arabic',
    'Natural Language :: Dutch',
    'Natural Language :: English',
    'Natural Language :: Finnish',
    'Natural Language :: French',
    'Natural Language :: German',
    'Natural Language :: Hebrew',
    'Natural Language :: Portuguese (Brazilian)',
    'Natural Language :: Russian',
    'Natural Language :: Spanish',
    'Natural Language :: Ukrainian',
    'Typing :: Typed',
]

[project.urls]
Documentation = 'https://betty.readthedocs.io'
GitHub = 'https://github.com/bartfeenstra/betty'

[project.entry-points.'console_scripts']
betty = 'betty.console:main_standalone'

[project.entry-points.'betty.plugin']
'asset-directory' = 'betty.asset:AssetDirectoryDefinition'
'command' = 'betty.console.command:CommandDefinition'
'content-builder' = 'betty.content:ContentBuilderDefinition'
'copyright-notice' = 'betty.copyright_notice:CopyrightNoticeDefinition'
'css-resource' = 'betty.html.css:CssResourceDefinition'
'document-provider' = 'betty.document:DocumentProviderDefinition'
'enricher' = 'betty.load:EnricherDefinition'
'entity' = 'betty.entity:EntityDefinition'
'event-type' = 'betty.event_type:EventTypeDefinition'
'extension' = 'betty.extension:ExtensionDefinition'
'gender' = 'betty.gender:GenderDefinition'
'http-rate-limit' = 'betty.http_client.rate_limit:RateLimitDefinition'
'jinja-filter' = 'betty.jinja.filter:JinjaFilterDefinition'
'jinja-test' = 'betty.jinja.test:JinjaTestDefinition'
'js-resource' = 'betty.html.js:JsResourceDefinition'
'license' = 'betty.license:LicenseDefinition'
'link' = 'betty.link:LinkDefinition'
'loader' = 'betty.load:LoaderDefinition'
'media-type' = 'betty.media_type:MediaTypeDefinition'
'place-type' = 'betty.place_type:PlaceTypeDefinition'
'renderer' = 'betty.render:RendererDefinition'
'role' = 'betty.role:RoleDefinition'
'serializer' = 'betty.serialize:SerializerDefinition'
'server' = 'betty.server:ServerDefinition'

[project.entry-points.'betty.asset_directory']
'builtin' = 'betty.asset_directories.builtin:BUILTIN'
'htt-api-doc' = 'betty.asset_directories.http_api_doc:HTTP_API_DOC'
'maps' = 'betty.asset_directories.maps:MAPS'
'project' = 'betty.asset_directories.project:_discover'
'raspberry-mint' = 'betty.asset_directories.raspberry_mint:RASPBERRY_MINT'
'trees' = 'betty.asset_directories.trees:TREES'
'webpack' = 'betty.asset_directories.webpack:WEBPACK'
'wiki' = 'betty.asset_directories.wiki:WIKI'

[project.entry-points.'betty.command']
'about' = 'betty.commands.about:About'
'clear-caches' = 'betty.commands.clear_caches:ClearCaches'
'config' = 'betty.commands.config:Config'
'demo' = 'betty.commands.demo:Demo'
'dev-profile-demo' = 'betty.commands.dev_profile_demo:_discover'
'dev-update-translations' = 'betty.commands.dev_update_translations:_discover'
'docs' = 'betty.commands.docs:Docs'
'generate' = 'betty.commands.generate:Generate'
'new' = 'betty.commands.new:New'
'new-translation' = 'betty.commands.new_translation:NewTranslation'
'serve' = 'betty.commands.serve:Serve'
'update-translations' = 'betty.commands.update_translations:UpdateTranslations'

[project.entry-points.'betty.copyright_notice']
'project-author' = 'betty.copyright_notices.project_author:ProjectAuthor'
'project-configuration' = 'betty.project._plugin_discovery:_discover_copyright_notices'
'public-domain' = 'betty.copyright_notices.public_domain:PublicDomain'
'streetmix' = 'betty.copyright_notices.streetmix:Streetmix'
'wikipedia-contributors' = 'betty.copyright_notices.wikipedia_contributors:WikipediaContributors'

[project.entry-points.'betty.css_resource']
'webpack' = 'betty.css_resources.webpack:WEBPACK'

[project.entry-points.'betty.document_provider']
'webpack' = 'betty.document_providers.webpack:Webpack'

[project.entry-points.'betty.license']
'all-rights-reserved' = 'betty.licenses.all_rights_reserved:AllRightsReserved'
'project-configuration' = 'betty.project._plugin_discovery:_discover_licenses'
'public-domain' = 'betty.licenses.public_domain:PublicDomain'
'spdx' = 'betty.licenses.spdx:SpdxLicenseDiscoverer.discover_for'

[project.entry-points.'betty.link']
'betty-documentation' = 'betty.links.betty_documentation:BETTY_DOCUMENTATION'
'betty-github' = 'betty.links.betty_github:BETTY_GITHUB'
'http-api-doc' = 'betty.links.http_api_doc:HTTP_API_DOC'

[project.entry-points.'betty.loader']
'demo' = 'betty.loaders.demo:Demo'
'gramps' = 'betty.loaders.gramps:Gramps'

[project.entry-points.'betty.media_type']
'html' = 'betty.media_types.html:HTML'
'jinja' = 'betty.media_types.jinja:JINJA'
'json' = 'betty.media_types.json:JSON'
'json-ld' = 'betty.media_types.json_ld:JSON_LD'
'pdf' = 'betty.media_types.pdf:PDF'
'plain-text' = 'betty.media_types.plain_text:PLAIN_TEXT'
'svg' = 'betty.media_types.svg:SVG'
'yaml' = 'betty.media_types.yaml:YAML'

[project.entry-points.'betty.enricher']
'deriver' = 'betty.enrichers.deriver:Deriver'
'populate-links' = 'betty.enrichers.populate_links:PopulateLinks'
'privatizer' = 'betty.enrichers.privatizer:Privatizer'
'wiki' = 'betty.enrichers.wiki:Wiki'

[project.entry-points.'betty.entity']
'citation' = 'betty.entities.citation:Citation'
'enclosure' = 'betty.entities.enclosure:Enclosure'
'event' = 'betty.entities.event:Event'
'file' = 'betty.entities.file:File'
'file-reference' = 'betty.entities.file_reference:FileReference'
'link' = 'betty.entities.link:Link'
'note' = 'betty.entities.note:Note'
'person' = 'betty.entities.person:Person'
'person-name' = 'betty.entities.person_name:PersonName'
'place' = 'betty.entities.place:Place'
'place-name' = 'betty.entities.place_name:PlaceName'
'presence' = 'betty.entities.presence:Presence'
'source' = 'betty.entities.source:Source'

[project.entry-points.'betty.event_type']
'adoption' = 'betty.event_types.adoption:Adoption'
'baptism' = 'betty.event_types.baptism:Baptism'
'bar-mitzvah' = 'betty.event_types.bar_mitzvah:BarMitzvah'
'bat-mitzvah' = 'betty.event_types.bat_mitzvah:BatMitzvah'
'birth' = 'betty.event_types.birth:Birth'
'burial' = 'betty.event_types.burial:Burial'
'conference' = 'betty.event_types.conference:Conference'
'confirmation' = 'betty.event_types.confirmation:Confirmation'
'correspondence' = 'betty.event_types.correspondence:Correspondence'
'cremation' = 'betty.event_types.cremation:Cremation'
'death' = 'betty.event_types.death:Death'
'divorce' = 'betty.event_types.divorce:Divorce'
'divorce-announcement' = 'betty.event_types.divorce_announcement:DivorceAnnouncement'
'emigration' = 'betty.event_types.emigration:Emigration'
'engagement' = 'betty.event_types.engagement:Engagement'
'funeral' = 'betty.event_types.funeral:Funeral'
'immigration' = 'betty.event_types.immigration:Immigration'
'marriage' = 'betty.event_types.marriage:Marriage'
'marriage-announcement' = 'betty.event_types.marriage_announcement:MarriageAnnouncement'
'missing' = 'betty.event_types.missing:Missing'
'occupation' = 'betty.event_types.occupation:Occupation'
'project-configuration' = 'betty.project._plugin_discovery:_discover_event_types'
'residence' = 'betty.event_types.residence:Residence'
'retirement' = 'betty.event_types.retirement:Retirement'
'unknown' = 'betty.event_types.unknown:Unknown'
'will' = 'betty.event_types.will:Will'

[project.entry-points.'betty.extension']
'http-api-doc' = 'betty.extensions.http_api_doc:HttpApiDoc'
'maps' = 'betty.extensions.maps:Maps'
'raspberry-mint' = 'betty.extensions.raspberry_mint:RaspberryMint'
'spdx' = 'betty.extensions.spdx:Spdx'
'trees' = 'betty.extensions.trees:Trees'
'webpack' = 'betty.extensions.webpack:Webpack'
'wiki' = 'betty.extensions.wiki:Wiki'

[project.entry-points.'betty.gender']
'man' = 'betty.genders.man:Man'
'non-binary' = 'betty.genders.non_binary:NonBinary'
'project-configuration' = 'betty.project._plugin_discovery:_discover_genders'
'unknown' = 'betty.genders.unknown:Unknown'
'woman' = 'betty.genders.woman:Woman'

[project.entry-points.'betty.jinja_filter']
'build-content' = 'betty.jinja_filters.build_content:BuildContent'
'file' = 'betty.jinja_filters.file:File'
'format-datetime-datetime' = 'betty.jinja_filters.format_datetime_datetime:FormatDatetimeDatetime'
'format-degrees' = 'betty.jinja_filters.format_degrees:FormatDegrees'
'html-lang' = 'betty.jinja_filters.html_lang:HtmlLang'
'image-resize-cover' = 'betty.jinja_filters.image_resize_cover:ImageResizeCover'
'json-dump' = 'betty.jinja_filters.json_dump:JsonDump'
'json-load' = 'betty.jinja_filters.json_load:JsonLoad'
'localize' = 'betty.jinja_filters.localize:Localize'
'negotiate-has-dates' = 'betty.jinja_filters.negotiate_has_dates:NegotiateHasDates'
'select-has-dates' = 'betty.jinja_filters.select_has_dates:SelectHasDates'
'to-language-tag' = 'betty.jinja_filters.to_language_tag:ToLanguageTag'
'unique' = 'betty.jinja_filters.unique:Unique'
'url' = 'betty.jinja_filters.url:Url'
'webpack-entry-point-js' = 'betty.jinja_filters.webpack_entry_point_js:WebpackEntryPointJs'

[project.entry-points.'betty.jinja_test']
'has-file-references' = 'betty.jinja_tests.has_file_references:HasFileReferences'
'image-media-type-supported' = 'betty.jinja_tests.image_media_type_supported:ImageMediaTypeSupported'
'linked-data-dumpable' = 'betty.jinja_tests.linked_data_dumpable:LinkedDataDumpable'
'persistent-entity-id' = 'betty.jinja_tests.persistent_entity_id:PersistentEntityId'
'public' = 'betty.jinja_tests.public:Public'
'plugin' = 'betty.jinja_tests.plugin:Plugin.discover'


[project.entry-points.'betty.js_resource']
'webpack-entry-point-loader' = 'betty.js_resources.webpack_entry_point_loader:WEBPACK_ENTRY_POINT_LOADER'

[project.entry-points.'betty.place_type']
'borough' = 'betty.place_types.borough:Borough'
'building' = 'betty.place_types.building:Building'
'cemetery' = 'betty.place_types.cemetery:Cemetery'
'city' = 'betty.place_types.city:City'
'country' = 'betty.place_types.country:Country'
'county' = 'betty.place_types.county:County'
'department' = 'betty.place_types.department:Department'
'district' = 'betty.place_types.district:District'
'farm' = 'betty.place_types.farm:Farm'
'hamlet' = 'betty.place_types.hamlet:Hamlet'
'locality' = 'betty.place_types.locality:Locality'
'municipality' = 'betty.place_types.municipality:Municipality'
'neighborhood' = 'betty.place_types.neighborhood:Neighborhood'
'number' = 'betty.place_types.number:Number'
'parish' = 'betty.place_types.parish:Parish'
'project-configuration' = 'betty.project._plugin_discovery:_discover_place_types'
'province' = 'betty.place_types.province:Province'
'region' = 'betty.place_types.region:Region'
'state' = 'betty.place_types.state:State'
'street' = 'betty.place_types.street:Street'
'town' = 'betty.place_types.town:Town'
'unknown' = 'betty.place_types.unknown:Unknown'
'village' = 'betty.place_types.village:Village'

[project.entry-points.'betty.role']
'attendee' = 'betty.roles.attendee:Attendee'
'beneficiary' = 'betty.roles.beneficiary:Beneficiary'
'celebrant' = 'betty.roles.celebrant:Celebrant'
'informant' = 'betty.roles.informant:Informant'
'organizer' = 'betty.roles.organizer:Organizer'
'project-configuration' = 'betty.project._plugin_discovery:_discover_roles'
'speaker' = 'betty.roles.speaker:Speaker'
'subject' = 'betty.roles.subject:Subject'
'unknown' = 'betty.roles.unknown:Unknown'
'witness' = 'betty.roles.witness:Witness'

[project.entry-points.'betty.http_rate_limit']
'wikipedia-action-api' = 'betty.http_client.rate_limits.wikipedia_action_api:WIKIPEDIA_ACTION_API'
'wikipedia-rest-api' = 'betty.http_client.rate_limits.wikipedia_rest_api:WIKIPEDIA_REST_API'

[project.entry-points.'betty.serializer']
'json' = 'betty.serializers.json:Json'
'yaml' = 'betty.serializers.yaml:Yaml'

[project.entry-points.'betty.server']
'builtin' = 'betty.servers.project_builtin:ProjectBuiltinServer'

[project.entry-points.'betty.renderer']
'html' = 'betty.renderers.html:Html'
'plain-text' = 'betty.renderers.plain_text:PlainText'

[project.entry-points.'betty.content_builder']
'box' = 'betty.content_builders.box:Box'
'map' = 'betty.content_builders.map:Map'
'map-attribution' = 'betty.content_builders.map_attribution:MapAttribution'
'notes' = 'betty.content_builders.notes:Notes'
'raspberry-mint-citations' = 'betty.content_builders.raspberry_mint_citations:Citations'
'raspberry-mint-color-style' = 'betty.content_builders.raspberry_mint_color_style:ColorStyle'
'raspberry-mint-columns' = 'betty.content_builders.raspberry_mint_columns:Columns'
'raspberry-mint-enclosees' = 'betty.content_builders.raspberry_mint_enclosees:Enclosees'
'raspberry-mint-entity-card' = 'betty.content_builders.raspberry_mint_entity_card:EntityCard'
'raspberry-mint-external-links' = 'betty.content_builders.raspberry_mint_external_links:ExternalLinks'
'raspberry-mint-facts' = 'betty.content_builders.raspberry_mint_facts:Facts'
'raspberry-mint-families' = 'betty.content_builders.raspberry_mint_families:Families'
'raspberry-mint-file-referees' = 'betty.content_builders.raspberry_mint_file_referees:FileReferees'
'raspberry-mint-incomplete-translation-warning' = 'betty.content_builders.raspberry_mint_incomplete_translation_warning:IncompleteTranslationWarning'
'raspberry-mint-media' = 'betty.content_builders.raspberry_mint_media:Media'
'raspberry-mint-media-gallery' = 'betty.content_builders.raspberry_mint_media_gallery:MediaGallery'
'raspberry-mint-presences' = 'betty.content_builders.raspberry_mint_presences:Presences'
'raspberry-mint-section' = 'betty.content_builders.raspberry_mint_section:Section'
'raspberry-mint-timeline' = 'betty.content_builders.raspberry_mint_timeline:Timeline'
'render' = 'betty.content_builders.render:Render'
'static' = 'betty.content_builders.static:Static'
'tree' = 'betty.content_builders.tree:Tree'
'wikipedia-summary' = 'betty.content_builders.wikipedia_summary:WikipediaSummary'

[project.optional-dependencies]
setuptools = [
    'build ~= 1.3',
    'twine ~= 6.0',
    'wheel ~= 0.47.0',
]
test = [
    # Work around https://github.com/pnuckowski/aioresponses/issues/289.
    'aiohttp ~= 3.12, < 3.14',
    'aioresponses ~= 0.7.8',
    'coverage ~= 7.6',
    'packaging ~= 26.0',
    'puremagic ~= 2.0',
    'pytest ~= 9.0',
    'pytest-aioresponses ~= 0.3.0',
    'pytest-asyncio ~= 1.0',
    'pytest-mock ~= 3.14',
    'pytest-order ~= 1.3',
    'pytest-playwright-asyncio ~= 0.8.0',
    'pytest-xdist ~= 3.8',
    'requests ~= 2.32',
    'ruff ~= 0.15.0',
    'ty == 0.0.34',
    'types-babel ~= 2.11',
    'types-docutils ~= 0.21',
    'types-jsonschema ~= 4.23',
    'types-lxml >= 2024.9.16',
    'types-polib ~= 1.2',
    'types-pyyaml ~= 6.0',
    'types-requests ~= 2.32',
    'types-setuptools ~= 82.0',
    'virtualenv ~= 21.1',
    'yappi ~= 1.7',
    'yarl ~= 1.22',
    'betty[setuptools]',
]
development = [
    'pytest-repeat ~= 0.9.4',
    'betty[test]',
]
ci = [
    'codecov ~= 2.1',
    'betty[test]',
]

[tool.setuptools.packages.find]
where = ['.']
include = [
    'betty',
    'betty.*',
]
exclude = [
    'betty.tests',
    'betty.tests.*',
]

[tool.setuptools.package-data]
betty = [
    'py.typed',

    # Data.
    '../data/**/*',
    '../data/asset/builtin/public/localized/.error/*',

    # Webpack.
    '../.browserslistrc',
    '../tsconfig.json',
]

[tool.setuptools.exclude-package-data]
betty = [
    '__pycache__',
]
