[build-system]
requires = [
    'setuptools ~= 82.0',
]
build-backend = 'setuptools.build_meta'

[project]
version = '0.0.0'
name = 'betty'
description = 'Betty visualizes and publishes your family history by building interactive, encyclopedia-like genealogy websites out of your Gramps and GEDCOM family trees'
readme = 'README.md'
license = 'GPL-3.0-or-later'
license-files = ['LICENSE.txt']
authors = [
  {name = 'Bart Feenstra', email = 'bar@bartfeenstra.com'},
]
requires-python = '~= 3.13'
dependencies = [
    'aiofiles ~= 25.1',
    'aiohttp ~= 3.12',
    'aiohttp-client-cache ~= 0.14',
    'aiosqlite ~= 0.21',
    'babel ~= 2.16',
    'docutils ~= 0.21',
    'geopy ~= 2.4',
    'jinja2 ~= 3.1',
    'jsonschema ~= 4.23',
    'lxml ~= 6.0',
    'markupsafe ~= 3.0',
    'pdf2image ~= 1.17',
    'polib ~= 1.2',
    'Pillow ~= 12.0',
    'platformdirs ~= 4.3',
    'pyyaml ~= 6.0',
    'referencing ~= 0.37.0',
    'rich ~= 14.1',
    'rich-argparse ~= 1.7',
    'shibuya == 2026.1.9',
    'sphinx ~= 8.2',
    'sphinx-design ~= 0.7.0',
]
classifiers = [
    'Environment :: Console',
    'Intended Audience :: Developers',
    'Intended Audience :: End Users/Desktop',
    'Intended Audience :: Science/Research',
    'Programming Language :: JavaScript',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
    'Operating System :: MacOS :: MacOS X',
    'Operating System :: POSIX :: Linux',
    'Operating System :: Microsoft :: Windows',
    'Topic :: Internet',
    'Topic :: Scientific/Engineering :: Visualization',
    'Topic :: Sociology :: Genealogy',
    'Topic :: Sociology :: History',
    'Topic :: Software Development :: Code Generators',
    'Natural Language :: Arabic',
    'Natural Language :: Dutch',
    'Natural Language :: English',
    'Natural Language :: Finnish',
    'Natural Language :: French',
    'Natural Language :: German',
    'Natural Language :: Hebrew',
    'Natural Language :: Portuguese (Brazilian)',
    'Natural Language :: Russian',
    'Natural Language :: Spanish',
    'Natural Language :: Ukrainian',
    'Typing :: Typed',
]

[project.urls]
Documentation = 'https://betty.readthedocs.io'
GitHub = 'https://github.com/bartfeenstra/betty'

[project.entry-points.'console_scripts']
betty = 'betty.console:main_standalone'

[project.entry-points.'betty.plugin']
'command' = 'betty.console.command:CommandDefinition'
'content-provider' = 'betty.content_provider:ContentProviderDefinition'
'copyright-notice' = 'betty.copyright_notice:CopyrightNoticeDefinition'
'entity' = 'betty.model:EntityDefinition'
'event-type' = 'betty.event_type:EventTypeDefinition'
'extension' = 'betty.extension:ExtensionDefinition'
'gender' = 'betty.gender:GenderDefinition'
'http-rate-limit' = 'betty.http_client.rate_limit:RateLimitDefinition'
'license' = 'betty.license:LicenseDefinition'
'place-type' = 'betty.place_type:PlaceTypeDefinition'
'presence-role' = 'betty.presence_role:PresenceRoleDefinition'
'renderer' = 'betty.render:RendererDefinition'
'serializer' = 'betty.serde:SerializerDefinition'

[project.entry-points.'betty.command']
'about' = 'betty.console.command.commands.about:About'
'clear-caches' = 'betty.console.command.commands.clear_caches:ClearCaches'
'config' = 'betty.console.command.commands.config:Config'
'demo' = 'betty.console.command.commands.demo:Demo'
'docs' = 'betty.console.command.commands.docs:Docs'
'extension-new-translation' = 'betty.console.command.commands.extension_new_translation:ExtensionNewTranslation'
'extension-update-translations' = 'betty.console.command.commands.extension_update_translations:ExtensionUpdateTranslations'
'generate' = 'betty.console.command.commands.generate:Generate'
'new' = 'betty.console.command.commands.new:New'
'new-translation' = 'betty.console.command.commands.new_translation:NewTranslation'
'serve' = 'betty.console.command.commands.serve:Serve'
'update-translations' = 'betty.console.command.commands.update_translations:UpdateTranslations'

[project.entry-points.'betty.dev.command']
'dev-profile-demo' = 'betty.console.command.commands.dev_profile_demo:DevProfileDemo'
'dev-update-translations' = 'betty.console.command.commands.dev_update_translations:DevUpdateTranslations'

[project.entry-points.'betty.copyright_notice']
'project-author' = 'betty.copyright_notice.copyright_notices:ProjectAuthor'
'public-domain' = 'betty.copyright_notice.copyright_notices:PublicDomain'
'streetmix' = 'betty.copyright_notice.copyright_notices:Streetmix'
'wikipedia-contributors' = 'betty.copyright_notice.copyright_notices:WikipediaContributors'

[project.entry-points.'betty.license']
'all-rights-reserved' = 'betty.license.licenses:AllRightsReserved'
'public-domain' = 'betty.license.licenses:PublicDomain'

[project.entry-points.'betty.entity_type']
'citation' = 'betty.ancestry.citation:Citation'
'enclosure' = 'betty.ancestry.enclosure:Enclosure'
'event' = 'betty.ancestry.event:Event'
'file' = 'betty.ancestry.file:File'
'file-reference' = 'betty.ancestry.file_reference:FileReference'
'link' = 'betty.ancestry.link:Link'
'note' = 'betty.ancestry.note:Note'
'person' = 'betty.ancestry.person:Person'
'person-name' = 'betty.ancestry.person_name:PersonName'
'place' = 'betty.ancestry.place:Place'
'presence' = 'betty.ancestry.presence:Presence'
'source' = 'betty.ancestry.source:Source'

[project.entry-points.'betty.event_type']
'adoption' = 'betty.event_type.event_types:Adoption'
'baptism' = 'betty.event_type.event_types:Baptism'
'bar-mitzvah' = 'betty.event_type.event_types:BarMitzvah'
'bat-mitzvah' = 'betty.event_type.event_types:BatMitzvah'
'birth' = 'betty.event_type.event_types:Birth'
'burial' = 'betty.event_type.event_types:Burial'
'conference' = 'betty.event_type.event_types:Conference'
'confirmation' = 'betty.event_type.event_types:Confirmation'
'correspondence' = 'betty.event_type.event_types:Correspondence'
'cremation' = 'betty.event_type.event_types:Cremation'
'death' = 'betty.event_type.event_types:Death'
'divorce' = 'betty.event_type.event_types:Divorce'
'divorce-announcement' = 'betty.event_type.event_types:DivorceAnnouncement'
'emigration' = 'betty.event_type.event_types:Emigration'
'engagement' = 'betty.event_type.event_types:Engagement'
'funeral' = 'betty.event_type.event_types:Funeral'
'immigration' = 'betty.event_type.event_types:Immigration'
'marriage' = 'betty.event_type.event_types:Marriage'
'marriage-announcement' = 'betty.event_type.event_types:MarriageAnnouncement'
'missing' = 'betty.event_type.event_types:Missing'
'occupation' = 'betty.event_type.event_types:Occupation'
'residence' = 'betty.event_type.event_types:Residence'
'retirement' = 'betty.event_type.event_types:Retirement'
'unknown' = 'betty.event_type.event_types:Unknown'
'will' = 'betty.event_type.event_types:Will'

[project.entry-points.'betty.extension']
'demo' = 'betty.extension.demo:Demo'
'deriver' = 'betty.extension.deriver:Deriver'
'gramps' = 'betty.extension.gramps:Gramps'
'http-api-doc' = 'betty.extension.http_api_doc:HttpApiDoc'
'maps' = 'betty.extension.maps:Maps'
'privatizer' = 'betty.extension.privatizer:Privatizer'
'raspberry-mint' = 'betty.extension.raspberry_mint:RaspberryMint'
'spdx' = 'betty.extension.spdx:Spdx'
'trees' = 'betty.extension.trees:Trees'
'webpack' = 'betty.extension.webpack:Webpack'
'wiki' = 'betty.extension.wiki:Wiki'

[project.entry-points.'betty.gender']
'man' = 'betty.gender.genders:Man'
'non-binary' = 'betty.gender.genders:NonBinary'
'unknown' = 'betty.gender.genders:Unknown'
'woman' = 'betty.gender.genders:Woman'

[project.entry-points.'betty.place_type']
'borough' = 'betty.place_type.place_types:Borough'
'building' = 'betty.place_type.place_types:Building'
'cemetery' = 'betty.place_type.place_types:Cemetery'
'city' = 'betty.place_type.place_types:City'
'country' = 'betty.place_type.place_types:Country'
'county' = 'betty.place_type.place_types:County'
'department' = 'betty.place_type.place_types:Department'
'district' = 'betty.place_type.place_types:District'
'farm' = 'betty.place_type.place_types:Farm'
'hamlet' = 'betty.place_type.place_types:Hamlet'
'locality' = 'betty.place_type.place_types:Locality'
'municipality' = 'betty.place_type.place_types:Municipality'
'neighborhood' = 'betty.place_type.place_types:Neighborhood'
'number' = 'betty.place_type.place_types:Number'
'parish' = 'betty.place_type.place_types:Parish'
'province' = 'betty.place_type.place_types:Province'
'region' = 'betty.place_type.place_types:Region'
'state' = 'betty.place_type.place_types:State'
'street' = 'betty.place_type.place_types:Street'
'town' = 'betty.place_type.place_types:Town'
'unknown' = 'betty.place_type.place_types:Unknown'
'village' = 'betty.place_type.place_types:Village'

[project.entry-points.'betty.presence_role']
'attendee' = 'betty.presence_role.presence_roles:Attendee'
'beneficiary' = 'betty.presence_role.presence_roles:Beneficiary'
'celebrant' = 'betty.presence_role.presence_roles:Celebrant'
'informant' = 'betty.presence_role.presence_roles:Informant'
'organizer' = 'betty.presence_role.presence_roles:Organizer'
'speaker' = 'betty.presence_role.presence_roles:Speaker'
'subject' = 'betty.presence_role.presence_roles:Subject'
'unknown' = 'betty.presence_role.presence_roles:Unknown'
'witness' = 'betty.presence_role.presence_roles:Witness'

[project.entry-points.'betty.http_rate_limit']
'wikipedia-action-api' = 'betty.http_client.rate_limits:WikipediaActionApi'
'wikipedia-rest-api' = 'betty.http_client.rate_limits:WikipediaRestApi'

[project.entry-points.'betty.serializer']
'json' = 'betty.serde.serializers:Json'
'yaml' = 'betty.serde.serializers:Yaml'

[project.entry-points.'betty.renderer']
'html' = 'betty.render.html:Html'
'plain-text' = 'betty.render.plain_text:PlainText'

[project.entry-points.'betty.content_provider']
'-demo-incomplete-translation-warning' = 'betty.extension.demo.content_provider:_IncompleteTranslationWarning'
'box' = 'betty.content_provider.content_providers:Box'
'maps-map' = 'betty.extension.maps.content_provider:Map'
'maps-attribution' = 'betty.extension.maps.content_provider:Attribution'
'notes' = 'betty.content_provider.content_providers:Notes'
'raspberry-mint-citations' = 'betty.extension.raspberry_mint.content_provider:Citations'
'raspberry-mint-color-style' = 'betty.extension.raspberry_mint.content_provider:ColorStyle'
'raspberry-mint-columns' = 'betty.extension.raspberry_mint.content_provider:Columns'
'raspberry-mint-enclosees' = 'betty.extension.raspberry_mint.content_provider:Enclosees'
'raspberry-mint-entity-card' = 'betty.extension.raspberry_mint.content_provider:EntityCard'
'raspberry-mint-external-links' = 'betty.extension.raspberry_mint.content_provider:ExternalLinks'
'raspberry-mint-facts' = 'betty.extension.raspberry_mint.content_provider:Facts'
'raspberry-mint-families' = 'betty.extension.raspberry_mint.content_provider:Families'
'raspberry-mint-file-referees' = 'betty.extension.raspberry_mint.content_provider:FileReferees'
'raspberry-mint-media' = 'betty.extension.raspberry_mint.content_provider:Media'
'raspberry-mint-media-gallery' = 'betty.extension.raspberry_mint.content_provider:MediaGallery'
'raspberry-mint-presences' = 'betty.extension.raspberry_mint.content_provider:Presences'
'raspberry-mint-section' = 'betty.extension.raspberry_mint.content_provider:Section'
'raspberry-mint-timeline' = 'betty.extension.raspberry_mint.content_provider:Timeline'
'render' = 'betty.content_provider.content_providers:Render'
'trees-tree' = 'betty.extension.trees.content_provider:Tree'
'wiki-wikipedia-summary' = 'betty.extension.wiki.content_provider:WikipediaSummary'

[project.optional-dependencies]
setuptools = [
    'build ~= 1.3',
    'twine ~= 6.0',
    'wheel ~= 0.46.0',
]
test = [
    'aioresponses ~= 0.7.8',
    'coverage ~= 7.6',
    'packaging ~= 26.0',
    'puremagic ~= 1.28',
    'pytest ~= 9.0',
    'pytest-aioresponses ~= 0.3.0',
    'pytest-asyncio ~= 1.0',
    'pytest-mock ~= 3.14',
    'pytest-playwright-asyncio ~= 0.7.0',
    'pytest-xdist ~= 3.8',
    'requests ~= 2.32',
    'ruff ~= 0.15.0',
    'ty == 0.0.17',
    'types-aiofiles ~= 25.1',
    'types-babel ~= 2.11',
    'types-docutils ~= 0.21',
    'types-jsonschema ~= 4.23',
    'types-lxml >= 2024.9.16',
    'types-polib ~= 1.2',
    'types-pyyaml ~= 6.0',
    'types-requests ~= 2.32',
    'types-setuptools ~= 82.0',
    'virtualenv ~= 20.27',
    'yappi ~= 1.7',
    'yarl ~= 1.22',
    'betty[setuptools]',
]
development = [
    'pytest-repeat ~= 0.9.4',
    'betty[test]',
]
ci = [
    'codecov ~= 2.1',
    'betty[test]',
]

[tool.setuptools.packages.find]
where = ['.']
include = [
    'betty',
    'betty.*',
]
exclude = [
    'betty.tests',
    'betty.tests.*',
]

[tool.setuptools.package-data]
betty = [
    'py.typed',

    # Assets.
    '../assets/**/*',
    '../assets/public/localized/.error/*',
    'project/extension/*/assets/**/*',

    # JSON Schemas.
    'json/schemas/*',

    # JavaScript
    '../js/*',
    '../js/**/*',

    # Webpack.
    '../.browserslistrc',
    '../tsconfig.json',
    'project/extension/*/webpack/**/*',
]

[tool.setuptools.exclude-package-data]
betty = [
    '__pycache__',
]
