"""
System directories for Betty to store data in.

These directories must only be used in production/live environments, and must therefore be injected into anything
that needs it, so during testing temporary, isolated directories can be used.
"""

from __future__ import annotations

from pathlib import Path
from typing import Final

import platformdirs

from betty.about import is_development, version_major

_appname: Final[str] = "betty"
_appauthor: Final[str] = "betty"

root_directory: Final[Path] = Path(__file__).resolve().parent.parent
"""
The betty installation root directory path.
"""

data_directory: Final[Path] = root_directory / "data"
"""
The data directory path.
"""

asset_directory: Final[Path] = data_directory / "asset"
"""
The asset directory path.
"""

builtin_asset_directory: Final[Path] = asset_directory / "builtin"
"""
The directory path to Betty's built-in assets.
"""

js_directory: Final[Path] = data_directory / "js"
"""
The directory path to Betty's built-in JavaScript components.
"""

webpack_entry_point_directory: Final[Path] = data_directory / "webpack"
"""
The directory path to Betty's built-in Webpack entry points.
"""

cache_directory: Final[Path] = platformdirs.user_cache_path(
    _appname, _appauthor, version_major
)
"""
The Betty instance's cache directory path on the local system.
"""

app_config_directory: Final[Path] = platformdirs.user_config_path(
    _appname, _appauthor, version_major
)
"""
The Betty instance's :py:class:`betty.app.App` configuration path on the local system.
"""

if is_development:
    dev_output_directory: Final[Path] = root_directory / "dev-output"
    """
    The output directory for artifacts generated by development tools.
    """
