"""
System directories for Betty to store data in.

These directories must only be used in production/live environments, and must therefore be injected into anything
that needs it, so during testing temporary, isolated directories can be used.
"""

from __future__ import annotations

from pathlib import Path
from typing import Final

import platformdirs

from betty.about import IS_DEVELOPMENT, VERSION_MAJOR

_APPNAME = "betty"
_APPAUTHOR = "betty"

ROOT_DIRECTORY: Final[Path] = Path(__file__).resolve().parent.parent
"""
The betty installation root directory path.
"""

DATA_DIRECTORY: Final[Path] = ROOT_DIRECTORY / "data"
"""
The data directory path.
"""

ASSET_DIRECTORY: Final[Path] = DATA_DIRECTORY / "asset"
"""
The asset directory path.
"""

BUILTIN_ASSET_DIRECTORY: Final[Path] = ASSET_DIRECTORY / "builtin"
"""
The directory path to Betty's built-in assets.
"""

JS_DIRECTORY: Final[Path] = DATA_DIRECTORY / "js"
"""
The directory path to Betty's built-in JavaScript components.
"""

WEBPACK_ENTRY_POINT_DIRECTORY: Final[Path] = DATA_DIRECTORY / "webpack"
"""
The directory path to Betty's built-in Webpack entry points.
"""

CACHE_DIRECTORY: Final[Path] = platformdirs.user_cache_path(
    _APPNAME, _APPAUTHOR, VERSION_MAJOR
)
"""
The Betty instance's cache directory path on the local system.
"""

APP_CONFIG_DIRECTORY: Final[Path] = platformdirs.user_config_path(
    _APPNAME, _APPAUTHOR, VERSION_MAJOR
)
"""
The Betty instance's :py:class:`betty.app.App` configuration path on the local system.
"""

if IS_DEVELOPMENT:
    DEV_OUTPUT_DIRECTORY: Final[Path] = ROOT_DIRECTORY / "dev-output"
    """
    The output directory for artifacts generated by development tools.
    """
