name: Remove pull request release

on:
  pull_request:
    types:
      - closed

jobs:
  delete-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@v4

      - name: Determine the tag
        run: echo 'betty_tag=0.0.0+dev-pull-request-${{ github.event.number }}' >> $GITHUB_ENV
        shell: bash

      - name: Delete the release
        run: gh release delete '${{ env.betty_tag }}' --cleanup-tag --yes
        env:
          GH_TOKEN: ${{ github.token }}
